### PR TITLE
xmlrpc: marshal integer values using an <int> tag

### LINKED ISSUE #128: Rpcmarshal.marshal never creates Rpc.Int32
There is a facility for encoding 32-bit integers into XMLRPC `<i4>` tag:
https://github.com/mirage/ocaml-rpc/blob/master/src/lib/xmlrpc.ml#L44
But this code is unreachable since `Rpcmarshal.marshal` still creates `Int` value instead of `Int32`:
```
# Rpcmarshal.marshal Rpc.Types.( Basic Int32 ) 42l ;;
- : Rpc.t = Rpc.Int 42L
```
While I'd expect `Rpc.Int32 42l` as a result. This conversion is forced here:
https://github.com/mirage/ocaml-rpc/blob/master/src/lib/rpc.ml#L152
And it looks like `Rpcmarshal.marshal` never creates `Int32` values at all.

This is an issue, say, for connecting ocaml-rpc to an existing pyhton XMLRPC code. The python library   reads  `<value>1</value>` as a string `'1'` value --  to get an integer value in python, one needs to encode it as  `<value><i4>1</i4></value>`.

### PR DESCRIPTION
**Pull request by mseri**
This should fix #128. And is more compliant with the standard. Compare it with 
https://github.com/mirage/ocaml-rpc/pull/130

### CODE REVIEW

**Comment by mseri** [comment]
This change should also be safe to merge, differently from the previous attempt

**Comment by gaborigloi** [comment]
In XML-RPC, `<int>` also denotes a 32-bit int, just like `<i4>` :( - so I think this means we cannot use it here because our 64-bit ints might be bigger than that?

**Comment by gaborigloi** [comment]
XML-RPC specification: http://xmlrpc.scripting.com/spec.html

**Comment by mseri** [comment]
But putting an int inside a value is worse: `If no type is indicated, the type is string.`
Python cheats and reads all values into unbounded integers for example, java uses extensions: https://ws.apache.org/xmlrpc/types.html (we may want to do the same then)

**Comment by mseri** [comment]
Otherwise we could use `<i8>`: https://stackoverflow.com/questions/18533309/xmlrpc-response-datatype-long-possible

**Comment by mseri** [comment]
And we already support i8: https://github.com/mirage/ocaml-rpc/pull/132/files#diff-4c11405176cb14ee0bdab7102ab0df9aR304

**Comment by gaborigloi** [comment]
Hmm, we could use `<i8>` then.
The only advantage of using just `<value>` is that we can send a 64-bit int as a string using standard clients to our rpc server. (And that's what xapi does too, it represents 64-bit ints as strings: https://xapi-project.github.io/xen-api/wire-protocol.html)

**Comment by mseri** [comment]
Indeed but that is a xapi implementation detail that goes against all other libraries behaviuor

**Comment by mseri** [comment]
We should check how much this change would break xapi, and if it does, maybe introduce a flag to enable the `i8` as an extension then

**Comment by mseri** [comment]
It shouldn't break xapi though, we had ditched the old xmlrpc in favour of ocaml-rpc some months ago, I wonder if we are using int32 anywhere... In the current code, the few instances are dealt with by hand: https://github.com/xapi-project/xen-api/blob/405b02e72f1ccc4f4b456fd52db30876faddcdd8/ocaml/xapi/vpx.ml#L218

**Comment by mseri** [comment]
The old code did not even take into account int64 or ints as strings: https://github.com/xapi-project/xen-api-libs-transitional/blob/master/http-svr/xMLRPC.ml

**Comment by gaborigloi** [comment]
Sounds good, let's add an optional flag to retain the old behaviour. Xapi will enable this flag.
This is required because currently xapi relies on this code for marshalling ints as strings. This is part of xapi's wire protocol.

**Comment by mseri** [comment]
I have updated the PR to add a flag to preserve the old behaviour (for now the default).

In the future we should make the correct behaviour (strict=true) the default (ping @edwintorok for a heads-up)

**Pull request merged**
