### PR TITLE
idl: make sure fns are added with correct name in GenServer(Exn), GenClient

### PR DESCRIPTION
**Pull request by gaborigloi**
The standard use case for the IDL is that we declare the RPC functions
in a functor taking an RPC module, and set the description in  that
module. So at that point when we call declare, the description may not
be set. When a user of the interface supplies the implementations of the
RPC functions, the description must be available, and therefore we know
the final wire name. Previously we constructed the wire name when the
description was still unset, resulting in an incorrect wire name or an
exception.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
I've tested this with some code and it seems to work.

**Comment by gaborigloi** [comment]
cc @mseri @jonludlam

**Comment by mseri** [comment]
Do `rpc_lwt` and `rpc_async` suffer from the same issue?

**Comment by gaborigloi** [comment]
Yes, good spot, they do. I've added a unit test that catches the issue.

**Comment by mseri** [comment]
At the moment these tests are not run by anything, can you add the plumbing to the Makefile? Is the commit to fix lwt and async missing?

**Comment by gaborigloi** [comment]
I didn't want to cause another merge conflict for your jbuilder PR, plus I found it hard to add them to the Makefile-based build system. So I can just take them out and re-add them later. But I do need to fix the Lwt and Async bindings.
Maybe we should merge your jbuilder PR first.

**Comment by mseri** [comment]
I think it's ok to leave the tests not runnig until the jbuilder PR, no need to remove them from this one. Please add a fix for the lwt and async bindings. I don't mind a rebase, it's quite fast to do, and I'd like to have a release with this fix before the jbuilder release.

**Comment by gaborigloi** [comment]
@mseri I've fixed the Async and Lwt bindings (I think). But we can only properly test it once it's jbuilderized ;)

**Comment by mseri** [comment]
Note, do not merge yet: after testing this and discussing this in person we agreed that there are still some changes needed.

**Pull request merged**
