### PR TITLE
Compatibility with rresult 0.7.0

### PR DESCRIPTION
**Pull request by psafont**
This version of rresult drops Result.result, Use Result.t instead

See https://github.com/ocaml/opam-repository/pull/19684

### CODE REVIEW

**Comment by mseri** [comment]
Can you add a lower bound to `rresult {>= "0.7.0"}` in the opam file?

**Comment by dbuenzli** [comment]
> This version of rresult drops Result.result,

Just to be precise :-) `rresult` drops the dependency on the `result` library which provides `Result.result` in your code.

**Comment by psafont** [comment]
> Can you add a lower bound to rresult {>= "0.7.0"} in the opam files?

I'm not sure that's necessary, tests run just fine when building with rresult 0.6.0

Current failure is due to pylint on the generated bindings

**Comment by mseri** [comment]
Looks good, thanks

**Pull request merged**
