### PR TITLE
pythongen: make code more pythonic

### PR DESCRIPTION
**Pull request by mseri**
There is still an outstanding issue: pythongen imports xapi and storage from xapi-storage.
I am going to fix it as well, but it's good to start reviewing the code

### CODE REVIEW

**Comment by mseri** [comment]
The last commit fixes the import thing.

@gaborigloi with this change, in xapi-storage you will have to use `of_interfaces helpers:"from xapi import *" interfaces`

The example stubs are still xapi and xapi.storage dependent, I am not yet sure how to fix them. Probably they need to be provided by the packages using the library. Not sure yet

**Comment by gaborigloi** [comment]
Could we add an annotation to `e.failure()` to make pylint work?

**Comment by mseri** [comment]
pylint will not work anyway as it does not like the long int syntax

**Comment by mseri** [comment]
I was able to run pylint on a buildenv, now the generated python passes pylint as well

**Comment by mseri** [comment]
And now we don't even need the pylint annotation

**Comment by gaborigloi** [comment]
We had an issue with the generated code where it was saying that "1423432 does not have type int64". We tried passing both with and without "L".

**Comment by gaborigloi** [comment]
The quicktests passed again :)

**Comment by mseri** [comment]
Let's merge. We can make further cleanups in subsequent PRs if needed

**Pull request merged**
