### PR TITLE
Cleanup and preparation for v5.6.0

### PR DESCRIPTION
**Pull request by mseri**
I will upstream this version, because we are way too many release behind

### CODE REVIEW

**Comment by mseri** [comment]
@gaborigloi do you know how `opam pin` infers the package version?

**Comment by gaborigloi** [comment]
I think we can either put the version into the opam file, or maybe say `opam pin ppx_deriving_rpc.5.6.0 ...`

**Comment by mseri** [comment]
I don't want to have to change also travis on updates. There must be a reasonable way

**Comment by gaborigloi** [comment]
Or maybe we could pin it like `opam pin ppx_deriving_rpc.master` - that should work, provided `master > 5.6.0`, or any other version number.

**Pull request merged**
