### PR TITLE
Support for calls with no parameters

### PR DESCRIPTION
**Pull request by tbrk**
Proposition for solving #169.

### CODE REVIEW

**Comment by mseri** [comment]
This actually looks fine. This "empty params" feels like a corner case of the spec to be fair, but so it is `null` which I think is an inconsistently supported extension.

Can you declare an "empty/void" call in `tests/common/test_interface.ml` and test it in `tests/lib/client_server_test.ml` to see what it looks like in practice?

**Comment by tbrk** [comment]
I agree. I had a very quick look last night to try to see what the spec said, but I don't think it considers this case. I guess the Python implementations used on servers define the spec 🤷.

**Comment by tbrk** [comment]
I've added those tests. They uncovered a bug in `Codegen` which I also fixed.

**Comment by mseri** [comment]
There are a few more fixes needed. If you run
    dune build @runexamples -p rpc
You should be able to reproduce the issue.
All the generators need fixing

**Comment by tbrk** [comment]
Done! I've also added a makefile target to build/test the examples.

**Comment by tbrk** [comment]
Extended example: https://github.com/tbrk/neos-server-ocaml-client

**Comment by mseri** [comment]
One last thing, sorry. Can you update the changelog

**Comment by mseri** [comment]
Thanks

**Comment by psafont** [comment]
Somehow this breaks the tests interfaces for xapi-idl. Was this meant to be a non-breaking change?

**Comment by mseri** [comment]
Yes, this was meant as non-breaking. I hoped the tests would pick up any breakage.
Do you have some suggestions on re-implementing it in a backward compatible way?

**Comment by psafont** [comment]
Adds methods to signature is going to be a breaking change for code that reimplements interfaces for testing purposes, I think a similar case happened with the calls not needing a response.

In any case I'll change the code when I upgrade, I just wanted to make you aware of this ;)

**Comment by mseri** [comment]
It is a good point. I did not think carefully enough about that. Sorry again for the disruption and thanks for the notification

**Comment by tbrk** [comment]
Sorry for the hassle @psafont. I think @mseri was just trying to help me out with a problem I had using this library call methods on a Python server. I wonder why the opam-repository regression testing didn't detect a problem with xapi-idl as a reverse dependency? (I looked back to the [pull request](https://github.com/ocaml/opam-repository/pull/20613) but CI log is no longer available.)

**Comment by psafont** [comment]
xapi-idl is not on opam-repository and instead it's in a dedicated opam repository, so it's normal it got missed.

Now that most of the xapi code is in the same repository it should be possible to easily upload it to the main opam-repository. I don't think it would be useful for any other reason but to check for breaking dependencies,and it would add a significant load to the CI, and add burden to the repository maintainers.

I prefer the occasional hassle, it part of my job anyway :)

**Comment by tbrk** [comment]
OK. Thanks for the explanation!

**Pull request merged**
