### PR TITLE
Add support for python3 and fix tests

### PR DESCRIPTION
**Pull request by mseri**
At a certain point we should just drop python2 support, but I think many people still rely on it.
Ping @lindig @gaborigloi to double check

### CODE REVIEW

**Comment by mseri** [comment]
I don't understand why it is not detecting ppx_deriving_rpc

**Comment by mseri** [comment]
That should do it. Keeping pyhon2 to run the scripts makes it work fine also on lts release of redhat and centos. Once we drop pyton2 support, we can also spend some more time modifying the tests

**Comment by gaborigloi** [comment]
cc @edwintorok - @mseri  can we add him as a collaborator - I cannot add him as reviewer ATM

**Comment by mseri** [comment]
@gaborigloi I don’t have the rights to add him. Maybe @jonludlam can. This PR does not change previous functionality besides adding python3 compatibility. I am going to open an issue where we can discuss the implication of dropping python2 compatibility

**Pull request merged**
