### PR TITLE
Update ppxlib

### PR DESCRIPTION
**Pull request by mseri**
This should fix https://github.com/mirage/ocaml-rpc/issues/156

### CODE REVIEW

**Comment by mseri** [comment]
Mmh it looks as if updating ppxlib requires dropping ocaml < 4.08

**Comment by anton-trunov** [comment]
Hi @mseri! Thanks for looking into this. CI is green now and it seems no dropping of OCaml < 4.08 is required.

**Comment by anton-trunov** [comment]
Btw, I tried compiling the project I'm working on with your branch and everything seems to work.

**Comment by mseri** [comment]
Yes I think there was some solver chaos before the latest ppxlib release. I will merge but I only have a mobile connection until the mid of next week. I will draft a release as soon as I get the new connection

**Comment by anton-trunov** [comment]
Awesome! Thank you and looking forward to a new release.

**Pull request merged**
